### ISSUE TITLE
Unable to switch playback address after full screen

### ISSUE THREAD

**Issue by Clushdada** [abdelaziz-mahdy/universal_video_controls#2]
How to switch playback address during full screen playback? The screen may get stuck. After exiting full screen, re-enter and resume normal operation!

**Comment by Clushdada** [comment]
Uploading IMG_6539.MP4…

**Comment by abdelaziz-mahdy** [comment]
> 
> Uploading IMG_6539.MP4…
> 
> 

I think the upload didn't finish

**Comment by abdelaziz-mahdy** [comment]
> How to switch playback address during full screen playback? The screen may get stuck. After exiting full screen, re-enter and resume normal operation!

Use the last version and call the update with new player to pass it to the full screen

**Comment by Clushdada** [comment]
> > How to switch playback address during full screen playback? The screen may get stuck. After exiting full screen, re-enter and resume normal operation!
> 
> Use the last version and call the update with new player to pass it to the full screen

I am using the latest version and still have this issue

**Comment by abdelaziz-mahdy** [comment]
Please provide a sample code and logs to reproduce the issue

**Comment by Clushdada** [comment]
_isLoading = true;
    _controller.dispose();
    _controller = initializeVideoPlayer(url);
    if (_isLoading) {
      _controller.initialize().then((_) {
        _isLoading = false;
        setState(() {});
      });
    }
    await Future.delayed(Duration(milliseconds: 300));
    _controller.play();
    setState(() {});

**Comment by Clushdada** [comment]
======== Exception caught by widgets library =======================================================
The following assertion was thrown building VideoControlsThemeDataInjector(dirty, state: _VideoControlsThemeDataInjectorState#91c1a):
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

The relevant error-causing widget was: 
  VideoControlsThemeDataInjector VideoControlsThemeDataInjector:file:///F:/muou_desktop/universal_video_controls/lib/universal_video_controls/src/controls/methods/fullscreen.dart:33:22
When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4558:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4572:6)
#2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4591:12)
#3      CupertinoVideoControlsTheme.maybeOf (package:universal_video_controls/universal_video_controls/src/controls/cupertino.dart:67:10)
#4      _VideoControlsThemeDataInjectorState.builders.<anonymous closure> (package:universal_video_controls/universal_video_controls/src/controls/widgets/video_controls_theme_data_injector.dart:49:49)
#5      _VideoControlsThemeDataInjectorState.build.<anonymous closure> (package:universal_video_controls/universal_video_controls/src/controls/widgets/video_controls_theme_data_injector.dart:97:34)
#6      ListBase.fold (dart:collection/list.dart:202:22)
#7      _VideoControlsThemeDataInjectorState.build (package:universal_video_controls/universal_video_controls/src/controls/widgets/video_controls_theme_data_injector.dart:95:21)

**Comment by Clushdada** [comment]
> ```
> _isLoading = true;
> _controller.dispose();
> _controller = initializeVideoPlayer(url);
> if (_isLoading) {
>   _controller.initialize().then((_) {
>     _isLoading = false;
>     setState(() {});
>   });
> }
> await Future.delayed(Duration(milliseconds: 300));
> _controller.play();
> setState(() {});
> ```

Changing the playback address in full screen mode will result in an error. Exiting full screen and then re-entering full screen will restore normal operation

**Comment by abdelaziz-mahdy** [comment]
Will check and give you a fix soon, I handled that in my player so it will be the same hopefully

**Comment by Clushdada** [comment]
> Will check and give you a fix soon, I handled that in my player so it will be the same hopefully

okay, thank you

**Comment by abdelaziz-mahdy** [comment]
this is my own handling of switching sources 
  keep in mind that 
  `late final GlobalKey<VideoControlsState> videoStateKey =
      GlobalKey<VideoControlsState>();`
    
and the widget `VideoControls(
                    key: videoStateKey,
                    autoDisposeControlsWrapper: false,` and i dispose all controllers on widget dispose 
    
  ```
  void initPlayer() {
    VideoPlayerController? oldController = controller;
    VideoPlayerControlsWrapper? oldWrapper = wrapper;

    if (_quality.value.isFile) {
      controller = VideoPlayerController.file(File(_quality.value.file!.path),
          httpHeaders: _quality.value.httpHeaders ?? {});
    } else {
      controller = VideoPlayerController.networkUrl(
          Uri.parse(_quality.value.url!),
          httpHeaders: _quality.value.httpHeaders ?? {});
    }

    wrapper = VideoPlayerControlsWrapper(controller!);
    videoStateKey.currentState?.update(player: wrapper!);
    setState(() {});
    oldController?.dispose();
    oldWrapper?.dispose();
  }
```

**Comment by Clushdada** [comment]
> this is my own handling of switching sources keep in mind that `late final GlobalKey<VideoControlsState> videoStateKey = GlobalKey<VideoControlsState>();`
> 
> and the widget and i dispose all controllers on widget dispose`VideoControls( key: videoStateKey, autoDisposeControlsWrapper: false,`
> 
> ```
> void initPlayer() {
>   VideoPlayerController? oldController = controller;
>   VideoPlayerControlsWrapper? oldWrapper = wrapper;
> 
>   if (_quality.value.isFile) {
>     controller = VideoPlayerController.file(File(_quality.value.file!.path),
>         httpHeaders: _quality.value.httpHeaders ?? {});
>   } else {
>     controller = VideoPlayerController.networkUrl(
>         Uri.parse(_quality.value.url!),
>         httpHeaders: _quality.value.httpHeaders ?? {});
>   }
> 
>   wrapper = VideoPlayerControlsWrapper(controller!);
>   videoStateKey.currentState?.update(player: wrapper!);
>   setState(() {});
>   oldController?.dispose();
>   oldWrapper?.dispose();
> }
> ```

Following your example, the issue of switching playback addresses in full screen mode still exists

**Comment by abdelaziz-mahdy** [comment]
Please provide a full code example since the issue does not exist in my case following the guidelines mentioned 

Or a GitHub repo 

Also logs

**Comment by abdelaziz-mahdy** [comment]
i am waiting for your code to be able to provide a better workaround

**Comment by Clushdada** [comment]
> i am waiting for your code to be able to provide a better workaround

[Video_Player_Demo.zip](https://github.com/user-attachments/files/16120122/Video_Player_Demo.zip)

**Comment by Clushdada** [comment]
> > i am waiting for your code to be able to provide a better workaround
> 
> [Video_Player_Demo.zip](https://github.com/user-attachments/files/16120122/Video_Player_Demo.zip)

Please run on the Windows platform

**Comment by abdelaziz-mahdy** [comment]
this is the correct example file migrated to my mentioned function 
```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:fvp/fvp.dart';
import 'package:universal_video_controls/universal_video_controls.dart';
import 'package:universal_video_controls/universal_video_controls/src/controls/material.dart';
import 'package:universal_video_controls/universal_video_controls/src/controls/material_desktop.dart';
import 'package:video_player/video_player.dart';
import 'package:video_player_demo/universal_video_controls_video_player.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  registerWith(
    options: {
      'platforms': ['windows', 'linux', 'macos', 'android'],
      // // 'video.decoders': ['FFmpeg'],
      // 'player': {
      //   'buffer': '2000+60000', // if data is not enough, cache 2s, max is 60s
      //   'demux.buffer.ranges': '8', // or other integer value as string
      //   'demux.buffer.protocols': 'file,http,https'
      // }
    },
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  VideoPlayerController? _controller;
  VideoPlayerControlsWrapper? _wrapper;
  late final GlobalKey<VideoControlsState> videoStateKey =
      GlobalKey<VideoControlsState>();

  Future<void> playerinit({required String url}) async {
    initializeVideoPlayer(url);

    await _controller?.initialize();
    _controller?.play();
    setState(() {});
  }

  void initializeVideoPlayer(String source) {
    VideoPlayerController? oldController = _controller;
    VideoPlayerControlsWrapper? oldWrapper = _wrapper;

    if (source.startsWith('http') || source.startsWith('https')) {
      _controller = VideoPlayerController.networkUrl(Uri.parse(source));
    } else if (source.startsWith('asset')) {
      _controller = VideoPlayerController.asset(source);
    } else {
      _controller = VideoPlayerController.file(File(source));
    }

    _wrapper = VideoPlayerControlsWrapper(_controller!);
    videoStateKey.currentState?.update(player: _wrapper!);
    setState(() {});
    oldController?.dispose();
    oldWrapper?.dispose();
  }

  @override
  void dispose() {
    _controller?.dispose();
    _wrapper?.dispose();
    // TODO: implement dispose
    super.dispose();
  }

  @override
  void initState() {
    playerinit(
        url:
            'https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4');
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: MaterialDesktopVideoControlsTheme(
      fullscreen: MaterialDesktopVideoControlsThemeData(
        seekBarThumbColor: Colors.blue,
        seekBarPositionColor: Colors.blue,
        toggleFullscreenOnDoublePress: false,
        // Modify bottom button bar:
        bottomButtonBar: [
          MaterialDesktopPlayOrPauseButton(),
          MaterialCustomButton(
              icon: Icon(Icons.skip_next),
              onPressed: () {
                playerinit(
                    url:
                        'https://user-images.githubusercontent.com/28951144/229373709-603a7a89-2105-4e1b-a5a5-a6c3567c9a59.mp4');
              }),
          MaterialDesktopVolumeButton(),
          MaterialDesktopPositionIndicator(),
          Spacer(),
          MaterialFullscreenButton()
        ],
      ),
      normal: const MaterialDesktopVideoControlsThemeData(
        // Modify theme options:
        seekBarThumbColor: Colors.blue,
        seekBarPositionColor: Colors.blue,
        toggleFullscreenOnDoublePress: false,
        // Modify top button bar:
        // Modify bottom button bar:
        bottomButtonBar: [
          MaterialDesktopPlayOrPauseButton(),
          MaterialDesktopVolumeButton(),
          MaterialDesktopPositionIndicator(),
          Spacer(),
          MaterialFullscreenButton()
        ],
      ),
      child: VideoControls(
        key: videoStateKey,
        fit: BoxFit.contain,
        player: VideoPlayerControlsWrapper(_controller!),
        autoDisposeControlsWrapper: false,
        controls: MaterialDesktopVideoControls,
      ),
    ));
  }
}

```

and as i mentioned upon doing this the error doesnt happen

**Comment by abdelaziz-mahdy** [comment]
also please use the package from pub 
```
  universal_video_controls_video_player: ^1.0.1
  universal_video_controls: ^1.0.15
```

since your local version is corrupted somehow
