### ISSUE TITLE
Playback stops when switching to fullscreen

### ISSUE THREAD

**Issue by kbublitz** [abdelaziz-mahdy/universal_video_controls#5]
Hi, I found another issue with using the video controls.

When switching to fullscreen or back to normal while the video is playing, the playback stops.
This happens on all the examples on https://abdelaziz-mahdy.github.io/universal_video_controls/ so it's easy enough to reproduce.

It would be nice if the video kept playing when switching fullscreen state.

**Comment by abdelaziz-mahdy** [comment]
What platform are you testing on, since for me it is still playing correctly

**Comment by kbublitz** [comment]
I tested on my Windows 10 system, both in Firefox (130.0.1) and Chrome (128.0.6613.139) the playback stops.

**Comment by abdelaziz-mahdy** [comment]
> I tested on my Windows 10 system, both in Firefox (130.0.1) and Chrome (128.0.6613.139) the playback stops.
>

will look into it, It looks like a race condition, since it's working for me and not working for you then will make sure there is some type of locking

**Comment by kbublitz** [comment]
Thank you, yes it looks like some kind of race condition. I added a debugPrint in fullscreen.dart to print the playing state and now it sometimes works and simetimes it doesn't. The output will either print true or false kind of randomly.

![grafik](https://github.com/user-attachments/assets/4666db35-ec5b-4166-86c8-13479bc678b4)

**Comment by abdelaziz-mahdy** [comment]
i did a commit it should fix the issue, but can you try it since the issue doesnt happen for me :( so i am not sure

**Comment by abdelaziz-mahdy** [comment]
also i would like to note, this is a problem only on web

**Comment by abdelaziz-mahdy** [comment]
@kbublitz i will wait for your confirmation before publishing the new version, i did update the code to compile to wasm too so i guess thats is better

**Comment by exomo** [comment]
thanks @abdelaziz-mahdy for the quick change, I'll test it toaday and let you know the results

**Comment by exomo** [comment]
Good news @abdelaziz-mahdy, 
I tested it quite extensively both on my work computer and my private computer and it works pretty well with the new changes.
I didn't have any issues when clicking the "maximize" button.

However I still had a few occasions where the video stopped when I double clicked it to maximize. Not sure if there is some separate code for the fullscreen button and the double click handler, or this is just another weird behavior of flutter for web.

Still I'd say the behavior is massively improved and I'm happy with the fix, thank you.

**Comment by abdelaziz-mahdy** [comment]
> Good news @abdelaziz-mahdy, 
> I tested it quite extensively both on my work computer and my private computer and it works pretty well with the new changes.
> I didn't have any issues when clicking the "maximize" button.
> 
> However I still had a few occasions where the video stopped when I double clicked it to maximize. Not sure if there is some separate code for the fullscreen button and the double click handler, or this is just another weird behavior of flutter for web.
> 
> Still I'd say the behavior is massively improved and I'm happy with the fix, thank you.
> 

Yes the double click is stable, but if the user knows that a click on video will pause then they will be ready if in full screen it was paused 


Ok I will publish the update today after finishing some stuff, thank you for testing it ❤️

**Comment by abdelaziz-mahdy** [comment]
i am very sorry, i forgot to publish the changes, published in `1.0.21`
